In [ ]:
import numpy as np
a = np.array ([[1,2,3], [4,5,6]])
a.shape


(2, 3)

In [ ]:
# Initialize a Python list
python_list = [2, 4, 6, 8, 10]
python_list

# Import numpy Library
import numpy as np

# Converting the python_list to a numpy array
numpy_array1 = np.array (python_list)

# Displays the numpy array
numpy_array1

array([ 2,  4,  6,  8, 10])

In [ ]:
array_1 = np.array([[1,2,3,4], [2,3,4,5], [9,8,7,6]]) #Creating Array
print(array_1.shape)
array_1

(3, 4)


array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [9, 8, 7, 6]])

In [ ]:
# Create two python List say 'List_x' and 'List_your'
X_list = list(range(100000))
Y_list = list(range(100000))

# Import numpy Library
import numpy as np
# Create two numpy array (say 'X' and 'Y') using above two list
X = np.array(X_list)
Y = np.array(Y_list)








In [ ]:
# Create two python List say 'List_x' and 'List_your'
X_list = list(range(100000))
Y_list = list(range(100000))


# Import numpy Library
import numpy as np
# Create two numpy array (say 'X' and 'Y') using above two list
X = np.array(X_list)
Y = np.array(Y_list)

# Define a function to calculate sum
# using numpy arrays (X, Y)
def numpy_version():
# In numpy we can directly perform
# sum element-wise as
    Z = X + Y


In [ ]:
#creating Array by importing Numpy
import numpy as np
arr = np.array([[5,6,7], [8,9,10], [11,12,13], [1,2,3]])
arr

array([[ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13],
       [ 1,  2,  3]])

In [ ]:
#Size the Array
arr.size

12

In [ ]:
arr.dtype

dtype('int64')

In [ ]:
ary = np.array([["Ade", "joel"], ["fola", "tola"] ])
ary
type(ary)
ary.dtype

dtype('<U4')

In [ ]:
#creation of continuous integer
array = np.arange(11)
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
#creation of collections of zero and one

arr = np.zeros(5)
print(np.array(arr))
aray = np.ones(5)
aray

[0. 0. 0. 0. 0.]


array([1., 1., 1., 1., 1.])

In [ ]:
#linspace, it create equally space from each value
arr = np.linspace(start=2, stop=20, num=6)
arr

array([ 2. ,  5.6,  9.2, 12.8, 16.4, 20. ])

In [ ]:
list = [2, 5, 8, 6, 4, 12, 16, 15] #Challenge Coding Ai Planet
np.array(list)

array([ 2,  5,  8,  6,  4, 12, 16, 15])

In [ ]:
np.linspace(start=17, stop=31, num=50)


array([17.        , 17.28571429, 17.57142857, 17.85714286, 18.14285714,
       18.42857143, 18.71428571, 19.        , 19.28571429, 19.57142857,
       19.85714286, 20.14285714, 20.42857143, 20.71428571, 21.        ,
       21.28571429, 21.57142857, 21.85714286, 22.14285714, 22.42857143,
       22.71428571, 23.        , 23.28571429, 23.57142857, 23.85714286,
       24.14285714, 24.42857143, 24.71428571, 25.        , 25.28571429,
       25.57142857, 25.85714286, 26.14285714, 26.42857143, 26.71428571,
       27.        , 27.28571429, 27.57142857, 27.85714286, 28.14285714,
       28.42857143, 28.71428571, 29.        , 29.28571429, 29.57142857,
       29.85714286, 30.14285714, 30.42857143, 30.71428571, 31.        ])

In [ ]:
import numpy as np
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
d.ndim
d

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [ ]:
#creating Zeros with shapes
x = np.zeros(shape=(4,3))
print(x)
print(" ")
#creating Zeros with shapes
y = np.zeros(shape=(3,2))
y

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
 


array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
#creating ones with shapes
x = np.ones(shape=(4,3))
x

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
import numpy as np
arr = np.array([[50, 45, 56, 78],[78, 89, 59, 90],[89, 78, 69, 70],[67, 69, 89, 70],[90,89, 80, 84],[89, 59, 90, 78]])
arr.shape

newarr = arr.reshape(2, 6, 2)

print ("\nOriginal array:\n", arr)
print ("Reshaped array:\n", newarr)
print(newarr.shape)
print(arr.shape)


Original array:
 [[50 45 56 78]
 [78 89 59 90]
 [89 78 69 70]
 [67 69 89 70]
 [90 89 80 84]
 [89 59 90 78]]
Reshaped array:
 [[[50 45]
  [56 78]
  [78 89]
  [59 90]
  [89 78]
  [69 70]]

 [[67 69]
  [89 70]
  [90 89]
  [80 84]
  [89 59]
  [90 78]]]
(2, 6, 2)
(6, 4)


In [ ]:
# Flatten array
arr = np.array([[0, 2, 3], [7, 5, 6], [10,12,13]])
flatarr = arr.flatten()

print ("\nOriginal array:\n", arr)
print ("Fattened array:\n", flatarr)


Original array:
 [[ 0  2  3]
 [ 7  5  6]
 [10 12 13]]
Fattened array:
 [ 0  2  3  7  5  6 10 12 13]


In [ ]:
word = "Hello dear"
print (word.replace("dear", "Baby").upper()) #replacing dear and using uppercase

HELLO BABY


In [ ]:
arr = np.arange(16) #reshaping to 4 by 4
arr
np.reshape(arr, (4,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
L = [10, 2, 7, 8, 3, 22, 54, 12, 13, 46, 23, 25, 41]
arr = np.array(L) #converting list to array
arr
p= np.sort(arr) #sorting accordingly
print(p)
np.delete(p,4)  #removing the fifth element

[ 2  3  7  8 10 12 13 22 23 25 41 46 54]


array([ 2,  3,  7,  8, 12, 13, 22, 23, 25, 41, 46, 54])

In [ ]:
L = [10, 2, 7, 8, 3, 22, 54, 12, 13, 46, 23, 25, 41]
arr = np.array(L)
arr = np.append(arr,53) #adding 53 to the array
arr
newarr = np.reshape(arr, (2,7)) #reshaping the array
newarr

array([[10,  2,  7,  8,  3, 22, 54],
       [12, 13, 46, 23, 25, 41, 53]])

In [ ]:
arr = np.array([10,20,30,40])
np.ndim(arr)
np.shape(arr)
np.reshape(arr,(2,2))

array([[10, 20],
       [30, 40]])

In [ ]:
#Nested list indexing
L = [[1,2,3,4], [5,6,7,8], [9,10,11,12]]
print(L[1][2]) #index 1, element 3
print(L[2][1]) #index 2, element 2


7
10


In [ ]:
arr = np.arange(15)
p = arr
c = np.reshape(p, (3,5))
print(c)
c[2, 3]

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


13