In [29]:
import pandas as pd
#creating series using python list
List = [1,1,2,3,5,8,13]
p_series = pd.Series(List)
p_series

0     1
1     1
2     2
3     3
4     5
5     8
6    13
dtype: int64

In [ ]:
#creating series using Dic
dic_l = {"one":1, "Two": 2, "Three":3}
l_series = pd.Series(dic_l)
l_series

one      1
Two      2
Three    3
dtype: int64

In [31]:

import numpy as np
#creating ndarry, find the shape, reshape and slicing
data = np.array([[1,25,40,65],[2,26,30,56],[3,27,35,62],[4,24,43,67]])
print (data)
print(" ")
print (data.ndim) #dimension of the data array
print(" ")
print (data.shape) #shape of the data
resha = np.reshape(data, (8,2)) #reshaping the array
print (resha)
print(" ")
print(data[1:4, 1:]) #slicing the data

[[ 1 25 40 65]
 [ 2 26 30 56]
 [ 3 27 35 62]
 [ 4 24 43 67]]
 
2
 
(4, 4)
[[ 1 25]
 [40 65]
 [ 2 26]
 [30 56]
 [ 3 27]
 [35 62]
 [ 4 24]
 [43 67]]
 
[[26 30 56]
 [27 35 62]
 [24 43 67]]


In [23]:
import numpy as np

data = np.array([[1,25,40,65],[2,26,30,56],[3,27,35,62],[4,24,43,67]])

import pandas as pd
dat_pd = pd.DataFrame(data, columns=["Reg. No","CCA /30", "Exams /70", "Total /100"], index=[1,2,3,4])
print (dat_pd)

   Reg. No  CCA /30  Exams /70  Total /100
1        1       25         40          65
2        2       26         30          56
3        3       27         35          62
4        4       24         43          67


In [26]:
#Using Dictionary to create my DataFrame in Pandas
data = { "Reg. No":[1,2,3,4,5,6],"CCA /30":[25,26,27,28,29,30], "Exams /70":[66,65,64,63,62,61], "Total /100": [91,91,91,91,91,91] }
datan = pd.DataFrame(data, index = [1,2,3,4,5,6]) #creating my personal index
datan

Reg. No  CCA /30  Exams /70  Total /100
1        1       25         66          91
2        2       26         65          91
3        3       27         64          91
4        4       28         63          91
5        5       29         62          91
6        6       30         61          91

In [46]:
import pandas as pd
readcal = pd.read_csv("sample_data/california_housing_test.csv")
print("The shape is: ", readcal.shape) #It display the shape
tal = readcal.head(8) #the head returns first 8 rows of the dataset
print("The First 8 Row of the Dataset: ", tal)
hal = readcal.tail(8) #the tail returns last 8 rows of the dataset
print("The Last 8 Row of the Dataset: ", hal)

The shape is:  (3000, 9)
The First 8 Row of the Dataset:     longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.05     37.37                27.0       3885.0           661.0   
1    -118.30     34.26                43.0       1510.0           310.0   
2    -117.81     33.78                27.0       3589.0           507.0   
3    -118.36     33.82                28.0         67.0            15.0   
4    -119.67     36.33                19.0       1241.0           244.0   
5    -119.56     36.51                37.0       1018.0           213.0   
6    -121.43     38.63                43.0       1009.0           225.0   
7    -120.65     35.48                19.0       2310.0           471.0   

   population  households  median_income  median_house_value  
0      1537.0       606.0         6.6085            344700.0  
1       809.0       277.0         3.5990            176500.0  
2      1484.0       495.0         5.7934            270500.0  
3        49.0 

In [47]:
import pandas as pd
readcal = pd.read_csv("sample_data/california_housing_test.csv")
readcal.info() #It provide a concise summary of your DataFrame

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   longitude           3000 non-null   float64
 1   latitude            3000 non-null   float64
 2   housing_median_age  3000 non-null   float64
 3   total_rooms         3000 non-null   float64
 4   total_bedrooms      3000 non-null   float64
 5   population          3000 non-null   float64
 6   households          3000 non-null   float64
 7   median_income       3000 non-null   float64
 8   median_house_value  3000 non-null   float64
dtypes: float64(9)
memory usage: 211.1 KB


In [11]:
import pandas as pd
readcal = pd.read_csv("sample_data/california_housing_test.csv")

readcal.loc[0:4, ["population", "households"]] #Indexing the DataFrame using Label for row o-4

population  households
0      1537.0       606.0
1       809.0       277.0
2      1484.0       495.0
3        49.0        11.0
4       850.0       237.0

from matplotlib import pyplot as plt
_df_5['population'].plot(kind='hist', bins=20, title='population')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_6['households'].plot(kind='hist', bins=20, title='households')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_7.plot(kind='scatter', x='population', y='households', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_8['population'].plot(kind='line', figsize=(8, 4), title='population')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_9['households'].plot(kind='line', figsize=(8, 4), title='households')
plt.gca().spines[['top', 'right']].set_visible(False)

In [4]:
import numpy as np
#creating ndarry, find the shape, reshape and slicing
data = np.array([[1,25,40,65],[2,26,30,56],[3,27,35,62],[4,24,43,67]])
print(data)
data[1, [0,1,2,3]]


[[ 1 25 40 65]
 [ 2 26 30 56]
 [ 3 27 35 62]
 [ 4 24 43 67]]


array([ 2, 26, 30, 56])

In [10]:
import pandas as pd
readcal = pd.read_csv("sample_data/california_housing_test.csv")

readcal.households == 606.0 #Conditional Selection, finding if the household contain the value 606.0 and return true/false

0        True
1       False
2       False
3       False
4       False
        ...  
2995    False
2996    False
2997    False
2998    False
2999    False
Name: households, Length: 3000, dtype: bool

In [35]:
dat = [1,2,3,4,5,6,1,2,1,2,3,4,1,2,3]
dat[1] = 10
dat
dat.sort()
len(dat)



15

In [46]:
import pandas as pd
p = pd.read_csv("https://raw.githubusercontent.com/dphi-official/Datasets/master/Standard_Metropolitan_Areas_Data-data.csv")
p
d = print (p.region == 2)

0     False
1      True
2     False
3      True
4     False
      ...  
94    False
95    False
96    False
97    False
98    False
Name: region, Length: 99, dtype: bool
